name: release

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
    - uses: goreleaser/goreleaser-action@v5.0.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
